labefood2/src/App.js, labefood2/src/constants/color.js, labefood2/src/constants/url.js, labefood2/src/global/GlobalContext.js, labefood2/src/global/GlobalState.js
=> :construction: components and globalState

labefood2/src/components/Intro/Intro.js, labefood2/src/pages/LogoPage/LogoPage.js
=> :rocket: LogoPage

labefood2/package-lock.json, labefood2/src/pages/CartPage/CartPage.js
=> :bug: conflito resolvido

labefood2/src/pages/LoginPage/LoginForm.js, labefood2/src/pages/LoginPage/LoginPage.js, labefood2/src/pages/SignUpAddressPage/SignUpAddressPage.js, labefood2/src/pages/SignUpPage/SignUpForm.js, labefood2/src/pages/SignUpPage/SignUpPage.js
=> :construction: Forms

labefood2/src/pages/EditProfilePage/EditProfilePage.js, labefood2/src/pages/LoginPage/LoginForm.js, labefood2/src/pages/LoginPage/LoginPage.js, labefood2/src/pages/LoginPage/styled.js, labefood2/src/pages/SignUpAddressPage/SignUpAddressForm.js, labefood2/src/pages/SignUpAddressPage/SignUpAddressPage.js, labefood2/src/pages/SignUpPage/SignUpForm.js, labefood2/src/pages/SignUpPage/SignUpPage.js, labefood2/src/styled.js
=> :lipstick: estilização algumas pages (sem funcionalidade total)

labefood2/src/pages/HomePage/HomePage.js, labefood2/src/pages/HomePage/styled.js
=> :rocket: Horizontal Scroll

labefood2/src/constants/token.js, labefood2/src/global/GlobalState.js, labefood2/src/hooks/useProtectedPage.js, labefood2/src/hooks/useRequest.js
=> 🚧 Organização de hooks, constants, requests

labefood2/src/services/resquests.js
=> :construction: inicio de requisições

labefood2/src/pages/LoginPage/LoginForm.js, labefood2/src/pages/SignUpPage/SignUpForm.js
=> :poop: juju plantão ajeitando o rejax

labefood2/src/pages/CartPage/CartPage.js, labefood2/src/pages/CartPage/styled.js
=> :lipstick: Estilização CartPage

labefood2/src/components/AddCart/AddCart.js, labefood2/src/components/AddCart/styled.js, labefood2/src/global/GlobalState.js, labefood2/src/pages/AddCartPage/AddCartPage.js
=> 🚧 Criação de componente AddCart

labefood2/src/global/GlobalState.js, labefood2/src/hooks/useRequest.js, labefood2/src/pages/HomePage/HomePage.js, labefood2/src/pages/UserProfilePage/UserProfilePage.js, labefood2/src/services/requests.js
=> :bug: Tentei resolver o bug do address kk

labefood2/src/components/CardHome/CardHome.js, labefood2/src/components/CardHome/styled.js, labefood2/src/components/RestItensCards/RestItensCards.js, labefood2/src/components/RestItensCards/styled.js, labefood2/src/constants/token.js, labefood2/src/global/GlobalState.js, labefood2/src/pages/HomePage/HomePage.js, labefood2/src/pages/RestDetailPage/RestDetailPage.js, labefood2/src/pages/SignUpAddressPage/SignUpAddressPage.js, labefood2/src/services/requests.js
=> :rocket: Renderizacao

labefood2/src/pages/RestDetailPage/RestDetailPage.js
=> :bug: Commit para renderizar

labefood2/src/pages/EditAddressPage/EditAddressPage.js, labefood2/src/pages/EditProfilePage/EditProfilePage.js, labefood2/src/pages/UserProfilePage/UserProfilePage.js, labefood2/src/services/requests.js
=> :rocket: edit profile and address page

labefood2/src/pages/HomePage/HomePage.js, labefood2/src/pages/HomePage/styled.js
=> :construction: Category Filter

labefood2/src/components/RestItensCards/styled.js
=> :bug: RestItensCard title

labefood2/src/pages/HomePage/HomePage.js
=> :rocket: função de buscar na home

labefood2/src/pages/EditAddressPage/EditAddressPage.js, labefood2/src/pages/EditProfilePage/EditProfilePage.js, labefood2/src/pages/LoginPage/LoginForm.js, labefood2/src/pages/SignUpAddressPage/SignUpAddressForm.js, labefood2/src/pages/SignUpPage/SignUpForm.js, labefood2/src/styled.js
=> :lipstick: Adiciona labels com localizacao correta

labefood2/src/pages/HomePage/HomePage.js
=> :rocket: Filtro de categoria

labefood2/src/components/AddCart/AddCart.js, labefood2/src/components/RestItensCards/RestItensCards.js, labefood2/src/global/GlobalState.js, labefood2/src/pages/RestDetailPage/RestDetailPage.js
=> :bug: Carrinho lógica

labefood2/src/pages/RestDetailPage/RestDetailPage.js, labefood2/src/pages/RestDetailPage/styled.js
=> :art: melhorias na estilização

labefood2/src/components/AddCart/AddCart.js, labefood2/src/components/RestItensCards/RestItensCards.js, labefood2/src/global/GlobalState.js, labefood2/src/pages/RestDetailPage/RestDetailPage.js
=> :tada: Adicionar itens ao carrinho

labefood2/src/pages/HomePage/HomePage.js, labefood2/src/pages/HomePage/styled.js
=> :art: Mostra qual categoria foi selecionada pela cor verde

labefood2/src/components/AddCart/AddCart.js, labefood2/src/components/AddCart/styled.js
=> ❇️  Adicionei um botão no componente addCart

labefood2/src/pages/UserProfilePage/UserProfilePage.js
=> :rocket: resolvido, logout funcionando

labefood2/src/components/AddCart/AddCart.js, labefood2/src/components/RestItensCards/RestItensCards.js, labefood2/src/global/GlobalState.js, labefood2/src/pages/CartPage/CartPage.js, labefood2/src/pages/RestDetailPage/RestDetailPage.js
=> 🚧  Informações do carrinho salvas no localStorage

labefood2/src/global/GlobalState.js, labefood2/src/routes/coordinator.js
=> :bug: Local Storage update bug fixed

labefood2/src/components/AddCart/AddCart.js, labefood2/src/components/RestItensCards/RestItensCards.js, labefood2/src/global/GlobalState.js, labefood2/src/pages/CartPage/CartPage.js
=> 💩 Gambiarra de lógica para rest vazio

labefood2/src/pages/UserProfilePage/UserProfilePage.js, labefood2/src/pages/UserProfilePage/styled.js
=> :art: correcao height endereço e botão logout

labefood2/src/pages/SignUpPage/SignUpForm.js, labefood2/src/pages/SignUpPage/styled.js
=> :art: :construction: olho aberto e fechado senha e começo bordavermelha

labefood2/src/components/CartCard/CartCard.js, labefood2/src/components/CartCard/styled.js, labefood2/src/components/Footer/styled.js, labefood2/src/pages/CartPage/CartPage.js, labefood2/src/pages/CartPage/styled.js, labefood2/src/pages/HomePage/HomePage.js, labefood2/src/pages/HomePage/styled.js, labefood2/src/services/requests.js
=> :rocket: adiciona envio de pedido

labefood2/src/components/ActiveOrder/ActiveOrder.js, labefood2/src/components/ActiveOrder/styled.js, labefood2/src/components/AddCart/AddCart.js, labefood2/src/global/GlobalState.js, labefood2/src/pages/CartPage/CartPage.js, labefood2/src/pages/CartPage/styled.js, labefood2/src/pages/HomePage/HomePage.js, labefood2/src/services/requests.js, labefood2/src/styled.js
=> :rocket: ActiveOrder funcionando zero bala e carrinho com condicional

labefood2/src/pages/CartPage/CartPage.js, labefood2/src/pages/HomePage/HomePage.js, labefood2/src/pages/UserProfilePage/UserProfilePage.js
=> :lipstick: Role do br

README.md
=> :rocket: readme 

labefood2/src/pages/LoginPage/LoginForm.js, labefood2/src/pages/SignUpPage/SignUpForm.js, labefood2/src/services/requests.js
=> :bug: agora vai, arrumamos o sign up

labefood2/src/services/requests.js
=> :bug: apaguei o alert da requisição de address
